name = "JLBoost"
uuid = "13d6d4a1-5e7f-472c-9ebc-8123a4fbb95f"
authors = ["Dai ZJ <zhuojia.dai@gmail.com>"]
version = "0.1.16"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LossFunctions = "30fc2ffe-d236-52d8-8643-a9d8f7c094a7"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SortingLab = "562c1548-17b8-5b69-83cf-d8aebec229f5"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
AbstractTrees = "0.3"
CategoricalArrays = "0.7, 0.8, 0.9"
DataFrames = "0.22"
LossFunctions = "0.5, 0.6"
MappedArrays = "0.2, 0.3"
Missings = "0.4, 1.0"
SortingLab = "^0.2.1"
StatsBase = "0.32, 0.33"
Tables = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VegaDatasets = "0ae4a718-28b7-58ec-9efb-cded64d6d5b4"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[targets]
test = ["Test"]
