name = "JLBoost"
uuid = "13d6d4a1-5e7f-472c-9ebc-8123a4fbb95f"
authors = ["Dai ZJ <zhuojia.dai@gmail.com>"]
version = "0.1.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JDF = "babc3d20-cd49-4f60-a736-a8f9c08892d3"
LossFunctions = "30fc2ffe-d236-52d8-8643-a9d8f7c094a7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SortingLab = "562c1548-17b8-5b69-83cf-d8aebec229f5"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DataFrames = "0.19"
JDF = "^0.2.8"
LossFunctions = "0.5"
MLJBase = "0.8"
Missings = "0.4"
SortingLab = "^0.2.1"
StatsBase = "0.32"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[targets]
test = ["Test"]
